# Generated by Django 2.0.7 on 2018-07-23 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='injection',
            options={'ordering': ['date'], 'verbose_name_plural': 'Injections'},
        ),
        migrations.AlterModelOptions(
            name='injectionsite',
            options={'ordering': ['name'], 'verbose_name_plural': 'Injection Sites'},
        ),
        migrations.AlterField(
            model_name='injection',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Injection Date'),
        ),
        migrations.AlterField(
            model_name='injectionsite',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='injectionsite',
            name='pos_x',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='injectionsite',
            name='pos_y',
            field=models.SmallIntegerField(),
        ),
    ]
