# Generated by Django 2.0.7 on 2018-07-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='frequency',
            field=models.CharField(choices=[('D', 'Every Day'), ('O', 'Every Other Day'), ('W', 'Every Week'), ('M', 'Every Monthly')], default='D', max_length=1),
        ),
    ]
