# Generated by Django 2.0.7 on 2018-07-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='frequency',
            field=models.IntegerField(choices=[(1, 'Every Day'), (2, 'Every Other Day'), (7, 'Every Week'), (30, 'Every Monthly')], default=1),
        ),
    ]
